apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: {{ arn }}
      username: system:node:{{ '{{EC2PrivateDNSName}}' }}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    {%- for user in users %}
    - userarn: {{ user.Arn }}
      username: {{ user.UserName }}
      groups:
        - system:masters
    {%- endfor %}